Display_Name: Mx.TE-33

# YOUR/BRAND IMAGE URL
Image_URL: /assets/images/profile.webp

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: /assets/images/album.png

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon
  - Dockerfile
  - README.md
  - nodemon.json
  - package.json
  - package-lock.json

# Default Markdown Engine
markdown: kramdown
